export const faqData =[
    {
        question : "How does your AI analysis software work?",
        answer : "Our AI analysis software utilizes computer vision and machine learning techniques to analyze the video footage of football and basketball matches. It automatically detects key events, such as goals, assists, fouls, and exceptional player performances. The software then generates highlight clips based on these events, providing users with concise and engaging summaries of the match.",
    },
    {
        question: " Can I download the analyzed match videos and highlights?",
        answer : "Yes, you have the option to download the analyzed match videos and highlights generated by our AI analysis software. This allows you to save and access them offline or share them with others as needed."
    },
    {
        question : "Which social networks and platforms do you support for match playback?",
        answer:"We support playback of analyzed match highlights on popular social networks such as YouTube, Facebook, Twitter, and Instagram. Once the match analysis is complete, you can easily share the generated highlights on these platforms or embed them on your own website or blog. Additionally, our cutting-edge stream integration allows you to broadcast live matches on YouTube and social media platforms, providing a seamless and engaging experience for your audience.",
    }
    
]